"""
Create the models
"""
from django.db import models


class Heroes(models.Model):
    hero_id = models.PositiveIntegerField(primary_key=True)
    localized_name = models.TextField()
    roles = models.TextField()
    primary_attr = models.TextField()
    attack_type = models.TextField()
    base_health = models.PositiveIntegerField()
    base_health_regen = models.FloatField()
    base_mana = models.PositiveIntegerField()
    base_mana_regen = models.FloatField()
    base_armor = models.FloatField()
    base_str = models.PositiveIntegerField()
    base_agi = models.PositiveIntegerField()
    base_int = models.PositiveIntegerField()
    str_gain = models.FloatField()
    agi_gain = models.FloatField()
    int_gain = models.FloatField()
    attack_range = models.PositiveIntegerField()
    attack_rate = models.FloatField()
    move_speed = models.PositiveIntegerField()


class GameStats(models.Model):
    # match_id = models.ForeignKey(Games, to_field='match_id', on_delete=models.CASCADE)
    match_id = models.PositiveIntegerField(primary_key=True)
    start_time = models.DateTimeField()
    duration = models.FloatField()
    account_id = models.PositiveIntegerField()
    hero_id = models.PositiveIntegerField()
    isRadiant = models.BooleanField()
    player_slot = models.PositiveIntegerField()
    level = models.PositiveIntegerField()
    xp_per_min = models.PositiveIntegerField()
    league_id = models.PositiveIntegerField()
    patch = models.PositiveIntegerField()
    radiant_score = models.PositiveIntegerField()
    dire_score = models.PositiveIntegerField()
    radiant_win = models.BooleanField()
    first_blood_time = models.FloatField()
    objectives = models.FloatField()
    game_mode = models.TextField()
    human_players = models.PositiveIntegerField()
    skill = models.FloatField()
    version = models.FloatField()
    region = models.TextField()
    total_xp = models.PositiveIntegerField()
    last_hits = models.PositiveIntegerField()
    hero_damage = models.PositiveIntegerField()
    kill_streaks = models.PositiveIntegerField()
    hero_healing = models.PositiveIntegerField()
    total_gold = models.PositiveIntegerField()
    kills = models.PositiveIntegerField()
    kda = models.PositiveIntegerField()
    rank_tier = models.PositiveIntegerField()
    deaths = models.PositiveIntegerField()
    randomed = models.BooleanField()
    net_worth = models.PositiveIntegerField()
    tower_damage = models.PositiveIntegerField()
    kills_per_min = models.FloatField()
    gold_per_min = models.PositiveIntegerField()
