# Generated by Django 3.2.2 on 2021-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('match_id', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('account_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('hero_id', models.PositiveIntegerField()),
                ('isRadiant', models.BooleanField()),
                ('player_slot', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('xp_per_min', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('league_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('patch', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('radiant_score', models.PositiveIntegerField()),
                ('dire_score', models.PositiveIntegerField()),
                ('radiant_win', models.BooleanField()),
                ('first_blood_time', models.FloatField(blank=True, default=None, null=True)),
                ('game_mode', models.TextField(blank=True, default=None, null=True)),
                ('human_players', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('skill', models.FloatField(blank=True, default=None, null=True)),
                ('version', models.FloatField(blank=True, default=None, null=True)),
                ('region', models.TextField(blank=True, default=None, null=True)),
                ('total_xp', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('last_hits', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('hero_damage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('kill_streaks', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('hero_healing', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('total_gold', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('kills', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('kda', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rank_tier', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('randomed', models.BooleanField(blank=True, default=None, null=True)),
                ('net_worth', models.FloatField(blank=True, default=None, null=True)),
                ('tower_damage', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('kills_per_min', models.FloatField(blank=True, default=None, null=True)),
                ('gold_per_min', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_0', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_1', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_2', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_3', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_4', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('item_5', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('hero_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('localized_name', models.TextField()),
                ('dname', models.TextField()),
                ('roles', models.JSONField(blank=True, default=None, null=True)),
                ('primary_attr', models.TextField(blank=True, default=None, null=True)),
                ('attack_type', models.TextField(blank=True, default=None, null=True)),
                ('base_health', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('base_health_regen', models.FloatField(blank=True, default=None, null=True)),
                ('base_mana', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('base_mana_regen', models.FloatField(blank=True, default=None, null=True)),
                ('base_armor', models.FloatField(blank=True, default=None, null=True)),
                ('base_str', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('base_agi', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('base_int', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('str_gain', models.FloatField(blank=True, default=None, null=True)),
                ('agi_gain', models.FloatField(blank=True, default=None, null=True)),
                ('int_gain', models.FloatField(blank=True, default=None, null=True)),
                ('attack_range', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('attack_rate', models.FloatField(blank=True, default=None, null=True)),
                ('move_speed', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
