# Generated by Django 2.2.5 on 2021-04-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('start_time', models.PositiveIntegerField()),
                ('radiant_score', models.PositiveIntegerField()),
                ('dire_score', models.PositiveIntegerField()),
                ('radiant_win', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_blood_time', models.PositiveIntegerField()),
                ('game_mode', models.PositiveIntegerField()),
                ('human_players', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('patch', models.PositiveIntegerField()),
                ('players', models.TextField()),
                ('objectives', models.TextField()),
                ('radiant_gold_adv', models.TextField()),
                ('radiant_xp_adv', models.TextField()),
                ('skill', models.FloatField()),
                ('region', models.PositiveIntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotaStatsApp.Games')),
            ],
        ),
    ]
