# Generated by Django 2.2.5 on 2021-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaStatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='match_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
